# Generated by Django 6.0.2 on 2026-03-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblcity',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('cityname', models.TextField(max_length=50)),
                ('stateid', models.IntegerField()),
            ],
        ),
    ]
