# Generated by Django 6.0.2 on 2026-03-02 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catname', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('cityname', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('clientid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.TextField(max_length=50)),
                ('bio', models.TextField(max_length=200)),
                ('cityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.city')),
            ],
        ),
        migrations.CreateModel(
            name='marketer',
            fields=[
                ('marketerid', models.AutoField(primary_key=True, serialize=False)),
                ('displayname', models.TextField(max_length=50)),
                ('displayimage', models.ImageField(upload_to='images/')),
                ('bio', models.TextField(max_length=200)),
                ('displayaddress', models.TextField(max_length=100)),
                ('displaycontact', models.TextField(max_length=20)),
                ('website', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='marketerimage',
            fields=[
                ('marketerimageid', models.AutoField(primary_key=True, serialize=False)),
                ('imageurl', models.ImageField(upload_to='images/')),
                ('marketerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.marketer')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('projectid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('status', models.TextField(max_length=20)),
                ('createdDT', models.DateTimeField(auto_now=True)),
                ('budget', models.FloatField()),
                ('mode', models.IntegerField()),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client')),
            ],
        ),
        migrations.CreateModel(
            name='projectservice',
            fields=[
                ('projectserviceid', models.AutoField(primary_key=True, serialize=False)),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.project')),
            ],
        ),
        migrations.CreateModel(
            name='quotation',
            fields=[
                ('quotationid', models.AutoField(primary_key=True, serialize=False)),
                ('budget', models.FloatField()),
                ('pdf', models.ImageField(upload_to='pdfs/')),
                ('description', models.TextField(max_length=200)),
                ('addedDT', models.DateTimeField(auto_now=True)),
                ('marketerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.marketer')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('reviewid', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.TextField(max_length=200)),
                ('rating', models.IntegerField()),
                ('reviewdate', models.DateTimeField(auto_now=True)),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client')),
                ('marketerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.marketer')),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.project')),
            ],
        ),
        migrations.CreateModel(
            name='savedproject',
            fields=[
                ('saveid', models.AutoField(primary_key=True, serialize=False)),
                ('marketerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.marketer')),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.project')),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('serviceid', models.AutoField(primary_key=True, serialize=False)),
                ('servicename', models.TextField(max_length=50)),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('stateid', models.AutoField(primary_key=True, serialize=False)),
                ('statename', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=20)),
                ('email', models.TextField(max_length=30)),
                ('profilepic', models.ImageField(upload_to='images/')),
                ('gender', models.TextField(max_length=10)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='tblcity',
        ),
        migrations.AddField(
            model_name='projectservice',
            name='serviceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.services'),
        ),
        migrations.AddField(
            model_name='city',
            name='stateid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.state'),
        ),
        migrations.AddField(
            model_name='marketer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='client',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
