# Generated by Django 6.0.2 on 2026-03-07 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category_city_client_marketer_marketerimage_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='clientid',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_reviews', to='user.user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='clientid',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.RemoveField(
            model_name='marketer',
            name='user',
        ),
        migrations.AlterField(
            model_name='savedproject',
            name='marketerid',
            field=models.ForeignKey(limit_choices_to={'role': 'marketer'}, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='marketerid',
            field=models.ForeignKey(limit_choices_to={'role': 'marketer'}, on_delete=django.db.models.deletion.CASCADE, related_name='marketer_reviews', to='user.user'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='marketerid',
            field=models.ForeignKey(limit_choices_to={'role': 'marketer'}, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='marketerimage',
            name='marketerid',
            field=models.ForeignKey(limit_choices_to={'role': 'marketer'}, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cityid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='displayaddress',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='displaycontact',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='displayimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='displayname',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('marketer', 'Marketer'), ('client', 'Client')], default='client', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='client',
        ),
        migrations.DeleteModel(
            name='marketer',
        ),
    ]
