# Generated by Django 6.0.2 on 2026-03-07 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_review_clientid_alter_project_clientid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='cityid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.city'),
        ),
    ]
