# Generated by Django 6.0.2 on 2026-03-07 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_role_alter_user_cityid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='discription',
        ),
        migrations.AlterField(
            model_name='marketerimage',
            name='marketerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='clientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='marketerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='clientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reviews', to='user.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='marketerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketer_reviews', to='user.user'),
        ),
        migrations.AlterField(
            model_name='savedproject',
            name='marketerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
