# Generated by Django 6.0.2 on 2026-03-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_description_project_discription_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='marketerimage',
            new_name='userimage',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='clientid',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='marketerid',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='clientid',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='userimage',
            old_name='marketerid',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='userimage',
            old_name='marketerimageid',
            new_name='userimageid',
        ),
        migrations.RemoveField(
            model_name='review',
            name='marketerid',
        ),
    ]
