# Generated by Django 6.0.2 on 2026-03-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_marketerimage_userimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedproject',
            old_name='marketerid',
            new_name='userid',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
