# Generated by Django 6.0.2 on 2026-03-07 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_marketerid_savedproject_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='userid',
            new_name='client_user',
        ),
        migrations.AddField(
            model_name='review',
            name='marketer_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marketer_reviews', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('marketer', 'Marketer'), ('client', 'Client')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('mix', 'Mix')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='cityid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.city'),
        ),
    ]
