# Generated by Django 6.0.2 on 2026-03-07 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_userid_review_client_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='projectid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.project'),
            preserve_default=False,
        ),
    ]
