# Generated by Django 6.0.2 on 2026-03-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_quotation_projectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
