# Generated by Django 6.0.3 on 2026-03-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_message_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='Service',
        ),
        migrations.AlterModelTable(
            name='category',
            table='user_category',
        ),
        migrations.AlterModelTable(
            name='city',
            table='user_city',
        ),
        migrations.AlterModelTable(
            name='message',
            table='user_message',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='user_notification',
        ),
        migrations.AlterModelTable(
            name='project',
            table='user_project',
        ),
        migrations.AlterModelTable(
            name='projectservice',
            table='user_projectservice',
        ),
        migrations.AlterModelTable(
            name='quotation',
            table='user_quotation',
        ),
        migrations.AlterModelTable(
            name='review',
            table='user_review',
        ),
        migrations.AlterModelTable(
            name='savedproject',
            table='user_savedproject',
        ),
        migrations.AlterModelTable(
            name='service',
            table='user_services',
        ),
        migrations.AlterModelTable(
            name='state',
            table='user_state',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_user',
        ),
        migrations.AlterModelTable(
            name='userimage',
            table='user_userimage',
        ),
    ]
