# Generated by Django 6.0.2 on 2026-03-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_services_service_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('userid', 'projectid')},
        ),
    ]
