# Generated by Django 6.0.2 on 2026-03-10 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_quotation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('client_user', 'projectid')},
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('userlanguageid', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=50)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'user_userlanguage',
                'unique_together': {('userid', 'language')},
            },
        ),
    ]
