# Generated by Django 6.0.2 on 2026-03-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_review_unique_together_userlanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='cityname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='createdDT',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='servicename',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='state',
            name='statename',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='displayaddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='displaycontact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='displayname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
